server:
  port: 8088

spring:
  application:
    name: auth-adapter

keycloak:
  base-uri: ${KEYCLOACK_SERVER:http://localhost:8091/auth/realms}
  authorization-uri: ${keycloak.base-uri}/bbq-management/protocol/openid-connect/auth
  user-info-uri: ${keycloak.base-uri}/bbq-management/protocol/openid-connect/userinfo
  token-uri: ${keycloak.base-uri}/bbq-management/protocol/openid-connect/token
  logout: ${keycloak.base-uri}/bbq-management/protocol/openid-connect/logout
  jwk-set-uri: ${keycloak.base-uri}/bbq-management/protocol/openid-connect/certs
  certs-id: ${KEYCLOACK_REAL_ID:3lgRIjhLSp7cE7CQhbtRwslRx9dr0VTJj3tS4fwF5JQ}
  client-id: front-bbq-app
  client-secret: qwerty
  scope: profile
  authorization-grant-type: password
  authorization-grant-type-refresh: refresh_token

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}

logging.level.root: INFO