server:
  port: 8093

spring:

  datasource:
    url: jdbc:sqlserver://unmsmserver.database.windows.net:1433;databaseName=unmsmdatabase
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    platform: mssql
    username: miguelarmas
    password: l21m01j16M01L13

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: true
