-- insert into menu_options(id, description, category, price, is_active) values (1, 'Ají de gallina', 'main-dish', 15, true);
-- insert into menu_options(id, description, category, price, is_active) values (2, 'Chancho al cilindro', 'main-dish', 25, false);
-- insert into menu_options(id, description, category, price, is_active) values (3, 'Jarra de chicha', 'drink', 12, true);
-- insert into menu_options(id, description, category, price, is_active) values (4, 'Jarra de maracuyá', 'drink', 12, true);
-- insert into menu_options(id, description, category, price, is_active) values (5, 'Torta de chocolate', 'dessert', 10, false);
-- insert into menu_options(id, description, category, price, is_active) values (6, 'Pie de manzana', 'dessert', 10, true);
