springdoc:
  swagger-ui:
    path: /swagger/index.html
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: "*"

author: Admin