#see for java tunning https://docs.oracle.com/cd/E15523_01/web.1111/e13814/jvm_tuning.htm#PERFM161
version: '3.8'
services:
  #Docker Compose creates a virtual network between the services and the DNS name 
  #used for each service is its name: that’s why it’s possible to use eureka-discovery as the hostname.
  ##########################################################################
  #registry-discovery-server
  ##########################################################################
  registry-discovery-server:
    container_name: registry-discovery-server-container
    image: bbq/registry-discovery-server-image:0.0.1-SNAPSHOT
    ports:
      - 8761:8761
    environment:
      - JAVA_OPTS=
        -Xms256M
        -Xmx256M

  ##########################################################################
  #config-server
  ##########################################################################
  config-server:
    container_name: config-server-container
    image: bbq/config-server-image:0.0.1-SNAPSHOT
    volumes:
      #this it use because we are using a local github repository /host/path:/container/path use ./ for relative path
      - ../demo-restful-api-config-server-repo:/tmp/config-server-repo
      #All projets will have a variable value  DEUREKA_SERVER this tell where find a registry-discovery server 
    environment:
      - EUREKA_SERVER=http://registry-discovery-server:8761/eureka/
      - LOCAL_REPOSITORY=/tmp/config-server-repo
      - JAVA_OPTS=
        -Xms256M
        -Xmx256M
      #-Dspring.cloud.config.server.native.searchLocations=/var/config-data
    depends_on:
      - registry-discovery-server
    ports:
      - 8888:8888

  ##########################################################################
  #admin-server
  ##########################################################################
  admin-server:
    container_name: admin-server-container
    image: bbq/admin-server-image:0.0.1-SNAPSHOT
      #All projets will have a variable value  DEUREKA_SERVER this tell where find a registry-discovery server 
    environment:
      - EUREKA_SERVER=http://registry-discovery-server:8761/eureka/
      - JAVA_OPTS=
        -Xms256M
        -Xmx256M
      #-Dspring.cloud.config.server.native.searchLocations=/var/config-data
    depends_on:
      - registry-discovery-server
    ports:
      - 8762:8762
      
  ##########################################################################
  #business-menu-option
  ##########################################################################
  business-menu-option:
    container_name: business-menu-option-container
    image: bbq/business-menu-option-image:0.0.1-SNAPSHOT
    environment:
      - EUREKA_SERVER=http://registry-discovery-server:8761/eureka/
      - JAVA_OPTS=
        -Xms256M
        -Xmx256M
    depends_on:
      - registry-discovery-server
      - config-server
    ports:
      - 8093:8093

  ##########################################################################
  #experience-consult-menu-option
  ##########################################################################
  experience-consult-menu-option:
    container_name: experience-consult-menu-option-container
    image: bbq/experience-consult-menu-option-image:0.0.1-SNAPSHOT
    environment:
      - EUREKA_SERVER=http://registry-discovery-server:8761/eureka/
      - BUSINESS_MENU_OPTION_BASE_PATH:http://business-menu-option:8093/bbq/business/v1/
      - Dspring.profiles.active=development #replace spring.cloud.config.profile in bootstrap.yml
      - JAVA_OPTS=
        -Xms256M
        -Xmx256M
    depends_on:
      - registry-discovery-server
      - config-server
    ports:
      - 8094:8094

 ##########################################################################     
 #database service
 ##########################################################################       
#  postgres_db:
#    container_name: postgres
#    image: postgres:latest
#    ports:
#        - 3432:5432
#    volumes:
#        #allow *.sql, *.sql.gz, or *.sh and is execute only if data directory is empty
#        - ./dbfiles:/docker-entrypoint-initdb.d
#        - /var/lib/postgres_data:/var/lib/postgresql/data
#    environment:
#        #default postgres super user
#        POSTGRES_USER: postgres
#         #default passwor for postgres super user, it is only the required envvar for postgres image
#        POSTGRES_PASSWORD: qwerty
#        #main database if name is not specific thname of super user is use
#        POSTGRES_DB: postgres

 ##########################################################################     
 #pgadmin service
 ##########################################################################  
#  pgadmin4:
#    image: dpage/pgadmin4
#    restart: always
#    environment:
#      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
#      PGADMIN_DEFAULT_PASSWORD: "qwerty"
#    ports:
#      - 80:80
#    depends_on:
#      - postgres_db
      


    