#server:
#  port: 8095
#
#eureka:
#  client:
#    serviceUrl:
##      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
#      defaultZone: EUREKA_SERVER
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#
#spring:
#  application:
#    name: business-dining-room-order

