#server:
#  port: 8094
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#
#spring:
#  application:
#    name: experience-consult-menu-option-v1